/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.slot;

import exception.ChonSai;
import exception.ChuaChon;
import java.awt.Color;
import java.awt.Font;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.PhieuDat;
import model.SlotDat;
import view.phieudat.HoaDonFrm;

/**
 *
 * @author My PC
 */
public class DSSlotThanhToanFrm extends javax.swing.JFrame {

    /**
     * Creates new form DSSlotThanhToanFrm
     */
    private PhieuDat pd;
    private DefaultTableModel bang;
    private HoaDonFrm gdhoadon;
    public DSSlotThanhToanFrm(PhieuDat pd, HoaDonFrm formhoadon) {
        this.setUndecorated(true);
        initComponents();
        setBackground(new Color(0, 0, 0, 0));
        setLocationRelativeTo(null);
        
        btnQuayLai.setBackground(new Color(0, 0, 0, 0));
        tblDanhSachSlot.getTableHeader().setBackground(new Color(0, 0, 0));
        
        tblDanhSachSlot.getTableHeader().setFont(new Font("Arial",1,20) {
        });
        this.pd = pd;
        this.gdhoadon= formhoadon;
        bang = (DefaultTableModel) tblDanhSachSlot.getModel();
        System.out.println(pd.getDsSlot().size());
        
        while(bang.getRowCount() > 0)
                bang.removeRow(0);
        for( SlotDat slot: pd.getDsSlot())
            bang.addRow(slot.toObject());
    }

    public HoaDonFrm getGdhoadon() {
        return gdhoadon;
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblDanhSachSlot = new javax.swing.JTable();
        btnQuayLai = new javax.swing.JButton();
        backGround = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1027, 636));
        getContentPane().setLayout(null);

        tblDanhSachSlot.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        tblDanhSachSlot.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã", "Tên", "Spa", "Ngày đặt", "Trạng thái"
            }
        ));
        tblDanhSachSlot.setRowHeight(30);
        tblDanhSachSlot.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDanhSachSlotMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblDanhSachSlot);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(230, 110, 750, 410);

        btnQuayLai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuayLaiActionPerformed(evt);
            }
        });
        getContentPane().add(btnQuayLai);
        btnQuayLai.setBounds(854, 531, 125, 46);

        backGround.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Group 63.png"))); // NOI18N
        getContentPane().add(backGround);
        backGround.setBounds(0, 0, 1027, 636);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblDanhSachSlotMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDanhSachSlotMouseClicked
        try {
            int row = tblDanhSachSlot.getSelectedRow();
            if(row < 0 || row >= tblDanhSachSlot.getRowCount()) throw new exception.ChuaChon();
            SlotDat slot = pd.getDsSlot().get(row);
            if( slot.getGhiChu().equals("chua nhan")) throw new exception.ChonSai();
            (new view.slot.ChiTietSlotDatFrm(slot, this)).setVisible(true);
            this.dispose();
        } catch (ChuaChon ex) {
            JOptionPane.showMessageDialog(this, "Chưa chọn slot");
        } catch (ChonSai ex) {
            JOptionPane.showMessageDialog(this, "Slot chưa được nhân");
        }
    }//GEN-LAST:event_tblDanhSachSlotMouseClicked

    private void btnQuayLaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuayLaiActionPerformed
        gdhoadon.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnQuayLaiActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backGround;
    private javax.swing.JButton btnQuayLai;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblDanhSachSlot;
    // End of variables declaration//GEN-END:variables
}
