/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.slot;

import exception.ChonSai;
import exception.ChuaChon;
import java.awt.Color;
import java.awt.Font;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.PhieuDat;
import model.SlotDat;

/**
 *
 * @author My PC
 */
public class DSSlotDatFrm extends javax.swing.JFrame {

    /**
     * Creates new form DSSlotDatFrm
     */
    private PhieuDat pd;
    private DefaultTableModel bang;
    public DSSlotDatFrm(PhieuDat pd) {
        this.setUndecorated(true);
        initComponents();
        txtTenKhachHang.setText(pd.getKh().getTen());
        setBackground(new Color(0, 0, 0, 0));
        setLocationRelativeTo(null);
        
        txtTenKhachHang.setBackground(new Color(0, 0, 0, 0));
        btnQuayLai.setBackground(new Color(0, 0, 0, 0));
        btnThuNho.setBackground(new Color(0, 0, 0, 0));
        
        tblKhachHang.getTableHeader().setFont(new Font("Arial", 1 , 24));
        
        this.pd = pd;
        txtTenKhachHang.setText(pd.getKh().getTen());
        bang = (DefaultTableModel) tblKhachHang.getModel();
       // System.out.println(pd.getDsSlot().size());
        
        while(bang.getRowCount() > 0)
                bang.removeRow(0);
        for( SlotDat slot: pd.getDsSlot())
            bang.addRow(slot.toObject());
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtTenKhachHang = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblKhachHang = new javax.swing.JTable();
        btnThuNho = new javax.swing.JButton();
        btnQuayLai = new javax.swing.JButton();
        backGround = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1320, 725));
        getContentPane().setLayout(null);

        txtTenKhachHang.setEditable(false);
        txtTenKhachHang.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        txtTenKhachHang.setBorder(null);
        txtTenKhachHang.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        getContentPane().add(txtTenKhachHang);
        txtTenKhachHang.setBounds(540, 120, 340, 60);

        tblKhachHang.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        tblKhachHang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã slot", "Tên dịch vụ", "Tên spa", "Ngày đặt", "Ghi chú"
            }
        ));
        tblKhachHang.setRowHeight(40);
        tblKhachHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblKhachHangMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblKhachHang);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(290, 190, 970, 480);
        getContentPane().add(btnThuNho);
        btnThuNho.setBounds(1180, 40, 40, 40);

        btnQuayLai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuayLaiActionPerformed(evt);
            }
        });
        getContentPane().add(btnQuayLai);
        btnQuayLai.setBounds(1240, 40, 40, 40);

        backGround.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Group 33.png"))); // NOI18N
        getContentPane().add(backGround);
        backGround.setBounds(0, 0, 1320, 720);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblKhachHangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblKhachHangMouseClicked
        try {
            int row = tblKhachHang.getSelectedRow();
            if(row < 0 || row >= tblKhachHang.getRowCount()) throw new exception.ChuaChon();
            SlotDat slot = pd.getDsSlot().get(row);
            if( slot.getGhiChu().equals("da nhan")) throw new exception.ChonSai();
            (new view.slot.NhapThongTinSlotDatFrm(slot)).setVisible(true);
            this.dispose();
        } catch (ChuaChon ex) {
            JOptionPane.showMessageDialog(this, "chưa chọn slot");
        } catch (ChonSai ex) {
            JOptionPane.showMessageDialog(this, "slot đã được nhân");
        }
                   
    }//GEN-LAST:event_tblKhachHangMouseClicked

    private void btnQuayLaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuayLaiActionPerformed
        new view.phieudat.TimPhieuDatFrm(pd.getNvDat()).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnQuayLaiActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backGround;
    private javax.swing.JButton btnQuayLai;
    private javax.swing.JButton btnThuNho;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblKhachHang;
    private javax.swing.JTextField txtTenKhachHang;
    // End of variables declaration//GEN-END:variables
}
