/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.slot;

import dao.SlotDatDAO;
import java.awt.Color;
import java.awt.Font;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.DichVuDung;
import model.NguyenLieuDung;
import model.PhieuDat;
import model.SlotDat;
import view.nguoidung.NhanVienFrm;

/**
 *
 * @author My PC
 */
public class NhapThongTinSlotDatFrm extends javax.swing.JFrame {

    /**
     * Creates new form NhapThongTinSlotDatFrm
     */
    private SlotDat slot;
    private PhieuDat pd;
    private ArrayList <DichVuDung> dsdv;
    private ArrayList <NguyenLieuDung> dsnl;
    private DefaultTableModel bangdv, bangnl;

    public SlotDat getSlot() {
        return slot;
    }

    
    public NhapThongTinSlotDatFrm(SlotDat slot) {
        this.setUndecorated(true);
        initComponents();
        setBackground(new Color(0, 0, 0, 0));
        setLocationRelativeTo(null);
        
        txtMaSlotDat.setBackground(new Color(0, 0, 0, 0));
        txtNgayGio.setBackground(new Color(0, 0, 0, 0));
        txtTenDichVu.setBackground(new Color(0, 0, 0, 0));
        txtTenSpa.setBackground(new Color(0, 0, 0, 0));
        btnNhapXong.setBackground(new Color(0, 0, 0, 0));
        btnThemDichVu.setBackground(new Color(0, 0, 0, 0));
        btnXoaNguyenLieu.setBackground(new Color(0, 0, 0, 0));
        btnThemNguyenLieu.setBackground(new Color(0, 0, 0, 0));
        btnXoaDichVu.setBackground(new Color(0, 0, 0, 0));
        btnThuNho.setBackground(new Color(0, 0, 0, 0));
        btnQuayLai.setBackground(new Color(0, 0, 0, 0));
        
        tblDichVu.getTableHeader().setFont(new Font("Arial", 1 , 18));
        tblNguyenLieu.getTableHeader().setFont(new Font("Arial", 1 , 18));
        
        this.slot = slot;
        dsdv = new ArrayList<>();
        dsnl = new ArrayList<>();
        txtMaSlotDat.setText(String.valueOf(slot.getMa()));
        txtTenDichVu.setText(slot.getSlot().getDichVu().getTen());
        txtTenSpa.setText(slot.getSlot().getSpa().getTen());
        txtNgayGio.setText(new SimpleDateFormat("yyyy-MM-dd HH:mm:ss").format(slot.getNgayGio()));
        bangdv = (DefaultTableModel) tblDichVu.getModel();
        bangnl = (DefaultTableModel) tblNguyenLieu.getModel();
        
        while(bangnl.getRowCount() > 0)
            bangnl.removeRow(0);
        while(bangdv.getRowCount() > 0)
            bangdv.removeRow(0);
    }
    
    
    public void capNhatNguyenLieuDung(NguyenLieuDung nld){
        dsnl.add(nld);
        bangnl.addRow(nld.toObject());
    }
    
    
    
    public void capNhatDichVuDung(DichVuDung dvd) {
       dsdv.add(dvd);
       bangdv.addRow(dvd.toObject());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtMaSlotDat = new javax.swing.JTextField();
        txtTenDichVu = new javax.swing.JTextField();
        txtTenSpa = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDichVu = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblNguyenLieu = new javax.swing.JTable();
        btnThemDichVu = new javax.swing.JButton();
        btnThemNguyenLieu = new javax.swing.JButton();
        btnXoaDichVu = new javax.swing.JButton();
        btnXoaNguyenLieu = new javax.swing.JButton();
        txtNgayGio = new javax.swing.JTextField();
        btnNhapXong = new javax.swing.JButton();
        btnThuNho = new javax.swing.JButton();
        btnQuayLai = new javax.swing.JButton();
        backGround = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1320, 724));
        getContentPane().setLayout(null);

        txtMaSlotDat.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        txtMaSlotDat.setBorder(null);
        txtMaSlotDat.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        txtMaSlotDat.setEnabled(false);
        getContentPane().add(txtMaSlotDat);
        txtMaSlotDat.setBounds(374, 125, 110, 30);

        txtTenDichVu.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        txtTenDichVu.setBorder(null);
        txtTenDichVu.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        txtTenDichVu.setEnabled(false);
        getContentPane().add(txtTenDichVu);
        txtTenDichVu.setBounds(570, 125, 280, 30);

        txtTenSpa.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        txtTenSpa.setBorder(null);
        txtTenSpa.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        txtTenSpa.setEnabled(false);
        getContentPane().add(txtTenSpa);
        txtTenSpa.setBounds(940, 125, 150, 30);

        tblDichVu.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        tblDichVu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tên", "Giá", "Khuyến mại", "Số lượng", "Thành tiền"
            }
        ));
        tblDichVu.setRowHeight(24);
        jScrollPane1.setViewportView(tblDichVu);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(235, 270, 500, 340);

        tblNguyenLieu.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        tblNguyenLieu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tên", "Giá", "Khuyến mại", "Số lượng", "Thành tiền"
            }
        ));
        tblNguyenLieu.setRowHeight(24);
        jScrollPane2.setViewportView(tblNguyenLieu);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(760, 270, 520, 340);

        btnThemDichVu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnThemDichVu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnThemDichVu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemDichVuActionPerformed(evt);
            }
        });
        getContentPane().add(btnThemDichVu);
        btnThemDichVu.setBounds(238, 618, 140, 52);

        btnThemNguyenLieu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnThemNguyenLieu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnThemNguyenLieu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemNguyenLieuActionPerformed(evt);
            }
        });
        getContentPane().add(btnThemNguyenLieu);
        btnThemNguyenLieu.setBounds(784, 618, 170, 52);

        btnXoaDichVu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnXoaDichVu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnXoaDichVu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaDichVuActionPerformed(evt);
            }
        });
        getContentPane().add(btnXoaDichVu);
        btnXoaDichVu.setBounds(394, 618, 142, 52);

        btnXoaNguyenLieu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnXoaNguyenLieu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnXoaNguyenLieu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaNguyenLieuActionPerformed(evt);
            }
        });
        getContentPane().add(btnXoaNguyenLieu);
        btnXoaNguyenLieu.setBounds(970, 618, 160, 52);

        txtNgayGio.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        txtNgayGio.setBorder(null);
        txtNgayGio.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        txtNgayGio.setEnabled(false);
        getContentPane().add(txtNgayGio);
        txtNgayGio.setBounds(640, 185, 210, 30);

        btnNhapXong.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnNhapXong.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnNhapXong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNhapXongActionPerformed(evt);
            }
        });
        getContentPane().add(btnNhapXong);
        btnNhapXong.setBounds(934, 177, 153, 52);

        btnThuNho.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnThuNho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThuNhoActionPerformed(evt);
            }
        });
        getContentPane().add(btnThuNho);
        btnThuNho.setBounds(1180, 30, 40, 40);

        btnQuayLai.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnQuayLai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuayLaiActionPerformed(evt);
            }
        });
        getContentPane().add(btnQuayLai);
        btnQuayLai.setBounds(1240, 30, 40, 40);

        backGround.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Group 32.png"))); // NOI18N
        getContentPane().add(backGround);
        backGround.setBounds(0, 0, 1320, 710);

        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(720, 590, 34, 14);

        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(720, 590, 34, 14);

        jTextField1.setText("jTextField1");
        getContentPane().add(jTextField1);
        jTextField1.setBounds(830, 580, 59, 20);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnThemNguyenLieuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemNguyenLieuActionPerformed
        (new view.nguyenlieu.TimNguyenLieuFrm(this)).setVisible(true);
    }//GEN-LAST:event_btnThemNguyenLieuActionPerformed

    private void btnThemDichVuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemDichVuActionPerformed
        (new view.dichvu.TimDichVuChiTietFrm(this)).setVisible(true);
    }//GEN-LAST:event_btnThemDichVuActionPerformed

    private void btnXoaDichVuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaDichVuActionPerformed
        int row = tblDichVu.getSelectedRow();
        if(row < 0 || row >= tblDichVu.getRowCount()){
            JOptionPane.showMessageDialog(this, "chưa chọn slot");
            return;
        }
            
        dsdv.remove(row);
        bangdv.removeRow(row);
    }//GEN-LAST:event_btnXoaDichVuActionPerformed

    private void btnXoaNguyenLieuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaNguyenLieuActionPerformed
        int row = tblNguyenLieu.getSelectedRow();
        if(row < 0 || row >= tblNguyenLieu.getRowCount()){
            JOptionPane.showMessageDialog(this, "chưa chọn slot");
            return;
        }
        dsnl.remove(row);
        bangnl.removeRow(row);
    }//GEN-LAST:event_btnXoaNguyenLieuActionPerformed

    private void btnNhapXongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNhapXongActionPerformed
        slot.setDsdv(dsdv);
        slot.setDsnl(dsnl);
        slot.setGhiChu("Đã nhận");
        //luu
        if(dsdv.size() <= 0 | dsnl.size() <= 0){
            JOptionPane.showMessageDialog(this, "Chưa nhập dịch vụ hoặc nguyên liệu");
        }else{
            SlotDatDAO slotDAO = new SlotDatDAO();
            if(slotDAO.nhanSlot(slot))
                JOptionPane.showMessageDialog(this, "thanh cong!");
            else
                JOptionPane.showMessageDialog(this, "khong thanh cong!");
             
        }
        (new NhanVienFrm(pd.getNvDat())).setVisible(true);
                this.dispose();
    }//GEN-LAST:event_btnNhapXongActionPerformed

    private void btnThuNhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThuNhoActionPerformed
        this.setExtendedState(JFrame.ICONIFIED);
    }//GEN-LAST:event_btnThuNhoActionPerformed

    private void btnQuayLaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuayLaiActionPerformed
        (new view.slot.DSSlotDatFrm(pd)).setVisible(true);
                    this.dispose();
    }//GEN-LAST:event_btnQuayLaiActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backGround;
    private javax.swing.JButton btnNhapXong;
    private javax.swing.JButton btnQuayLai;
    private javax.swing.JButton btnThemDichVu;
    private javax.swing.JButton btnThemNguyenLieu;
    private javax.swing.JButton btnThuNho;
    private javax.swing.JButton btnXoaDichVu;
    private javax.swing.JButton btnXoaNguyenLieu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTable tblDichVu;
    private javax.swing.JTable tblNguyenLieu;
    private javax.swing.JTextField txtMaSlotDat;
    private javax.swing.JTextField txtNgayGio;
    private javax.swing.JTextField txtTenDichVu;
    private javax.swing.JTextField txtTenSpa;
    // End of variables declaration//GEN-END:variables

    
}
