/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.slot;

import dao.SlotDAO;
import exception.ChuaChon;
import exception.DeTrong;
import exception.SaiNgay;
import java.awt.Color;
import java.awt.Font;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import model.NguoiDung;
import model.PhieuDat;
import model.Slot;
import model.SlotDat;
import view.nguoidung.QuanLyFrm;

/**
 *
 * @author My PC
 */
public class TimSlotFrm extends javax.swing.JFrame {

    /**
     * Creates new form TimSLotFrm
     */
    private ArrayList <Slot> dsslot;
    private ArrayList <SlotDat> dschon;
    private DefaultTableModel bang, chon;
    private NguoiDung nd;
    private String ngay ;
    private String gio ;
    public TimSlotFrm(NguoiDung nd) {
        this.setUndecorated(true);
        initComponents();
        setBackground(new Color(0, 0, 0, 0));
        setLocationRelativeTo(null);
        
        JTextField a = (JTextField) pkrNgayDat.getComponent(1); a.setEditable(false);
        pkrGioDat.setFont(new Font("Arial",1,24));
        pkrGioDat.setBackground(new Color(0, 0, 0, 0));
        pkrNgayDat.setBackground(new Color(0, 0, 0, 0));
        txtTenDichVu.setBackground(new Color(0, 0, 0, 0));
        btnChon.setBackground(new Color(0, 0, 0, 0));
        btnTimKiem.setBackground(new Color(0, 0, 0, 0));
        btnXoa.setBackground(new Color(0, 0, 0, 0));
        btnThuNho.setBackground(new Color(0, 0, 0, 0));
        btnThoat.setBackground(new Color(0, 0, 0, 0));
        
        tblSlot.getTableHeader().setBackground(Color.BLACK);
        tblSlot.getTableHeader().setFont(new Font("Arial", 1 , 14));
        
        tblSlotChon.getTableHeader().setBackground(new Color(0, 0, 0));
        tblSlotChon.getTableHeader().setFont(new Font("Arial", 1 , 14));
        
        dschon = new ArrayList<SlotDat>();
        bang =  (DefaultTableModel) tblSlot.getModel();
        chon =  (DefaultTableModel) tblSlotChon.getModel();
        this.nd = nd;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pkrNgayDat = new com.toedter.calendar.JDateChooser();
        pkrGioDat = new lu.tudor.santec.jtimechooser.JTimeChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSlot = new javax.swing.JTable();
        txtTenDichVu = new javax.swing.JTextField();
        btnTimKiem = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblSlotChon = new javax.swing.JTable();
        btnXoa = new javax.swing.JButton();
        btnChon = new javax.swing.JButton();
        btnThuNho = new javax.swing.JButton();
        btnThoat = new javax.swing.JButton();
        backGround = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1308, 712));
        getContentPane().setLayout(null);

        pkrNgayDat.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        getContentPane().add(pkrNgayDat);
        pkrNgayDat.setBounds(601, 112, 215, 38);

        pkrGioDat.setBackground(new java.awt.Color(255, 255, 255));
        pkrGioDat.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        getContentPane().add(pkrGioDat);
        pkrGioDat.setBounds(965, 111, 112, 38);

        tblSlot.setFont(new java.awt.Font("Arial", 0, 22)); // NOI18N
        tblSlot.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã", "Tên dịch vụ", "Tên spa", "Mô tả"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblSlot.setRowHeight(30);
        tblSlot.setSelectionBackground(new java.awt.Color(0, 153, 102));
        tblSlot.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblSlotMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblSlot);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(260, 250, 470, 330);

        txtTenDichVu.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        txtTenDichVu.setBorder(null);
        txtTenDichVu.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        getContentPane().add(txtTenDichVu);
        txtTenDichVu.setBounds(610, 181, 370, 37);

        btnTimKiem.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiemActionPerformed(evt);
            }
        });
        getContentPane().add(btnTimKiem);
        btnTimKiem.setBounds(1000, 170, 84, 52);

        tblSlotChon.setFont(new java.awt.Font("Arial", 0, 22)); // NOI18N
        tblSlotChon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã", "Tên dịch vụ", "Tên spa"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblSlotChon.setGridColor(new java.awt.Color(0, 204, 153));
        tblSlotChon.setRowHeight(30);
        tblSlotChon.setSelectionBackground(new java.awt.Color(0, 153, 102));
        jScrollPane2.setViewportView(tblSlotChon);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(780, 250, 490, 330);

        btnXoa.setBackground(new java.awt.Color(255, 51, 51));
        btnXoa.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        btnXoa.setForeground(new java.awt.Color(255, 255, 255));
        btnXoa.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });
        getContentPane().add(btnXoa);
        btnXoa.setBounds(795, 620, 146, 52);

        btnChon.setBackground(new java.awt.Color(51, 147, 80));
        btnChon.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        btnChon.setForeground(new java.awt.Color(255, 255, 255));
        btnChon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnChon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChonActionPerformed(evt);
            }
        });
        getContentPane().add(btnChon);
        btnChon.setBounds(600, 620, 145, 52);

        btnThuNho.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnThuNho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThuNhoActionPerformed(evt);
            }
        });
        getContentPane().add(btnThuNho);
        btnThuNho.setBounds(1163, 40, 40, 40);

        btnThoat.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThoatActionPerformed(evt);
            }
        });
        getContentPane().add(btnThoat);
        btnThoat.setBounds(1225, 40, 40, 40);

        backGround.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Group 24.png"))); // NOI18N
        getContentPane().add(backGround);
        backGround.setBounds(0, 0, 1310, 720);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiemActionPerformed
        
        try {
            
            Date ngayd = pkrNgayDat.getDate();
            if(ngayd == null ) throw new exception.DeTrong();
            ngay = new SimpleDateFormat("dd-MM-yyyy").format(ngayd);
            gio = pkrGioDat.getTimeField().getText();
            if(gio.compareTo("08:00:00") < 0 || gio.compareTo("20:00:00") > 0 ) throw new exception.SaiNgay();
            String tenDichVu = txtTenDichVu.getText().trim();
           // if(tenDichVu.length() == 0) throw new exception.DeTrong();
            
            
            SlotDAO slotDAO = new SlotDAO();
            try {
                
                Date ngaydat = new SimpleDateFormat("dd-MM-yyyy HH:mm:ss" ).parse(ngay + " " + gio);
                System.out.println(ngaydat);
                if(ngaydat.before(new Date())) throw new exception.SaiNgay();
                if(tenDichVu.length() == 0) throw new exception.DeTrong();
                dsslot = slotDAO.timSlotTrong(ngaydat, tenDichVu);
                
                while(bang.getRowCount() > 0)
                    bang.removeRow(0);
                for( Slot sl : dsslot){
                    bang.addRow(sl.toObject());
                    //System.out.println(sl);
                }
                
            }  catch (SaiNgay ex) {
                JOptionPane.showMessageDialog(this, "ngay đặt không hợp lệ");
            } catch (ParseException ex) {
                JOptionPane.showMessageDialog(this, "lỗi");
            }catch (DeTrong ex) {
                JOptionPane.showMessageDialog(this, "chưa nhập tên dịch vụ");
            } 
        }  catch (DeTrong ex) {
            JOptionPane.showMessageDialog(this, "chưa chọn ngày");
        } catch (SaiNgay ex) {
            JOptionPane.showMessageDialog(this, "ngoài giờ làm việc");
        }
    }//GEN-LAST:event_btnTimKiemActionPerformed

    private void tblSlotMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblSlotMouseClicked
        try {
            int row = tblSlot.getSelectedRow();
            if(row < 0 || row >= tblSlot.getRowCount())
                throw new exception.ChuaChon();
//            Date ngayd = txtNgayDat.getDate();
//            if(ngayd == null ) throw new exception.DeTrong();
//            String ngay = new SimpleDateFormat("dd-MM-yyyy").format(txtNgayDat.getDate());
//            String gio = txtGioDat.getTimeField().getText();    
            SlotDat slotDat = new SlotDat();
            slotDat.setSlot(dsslot.get(row));
            slotDat.setGhiChu("Chưa nhận");
            slotDat.setNgayGio(new SimpleDateFormat("dd-MM-yyyy HH:mm:ss" ).parse(ngay + " " + gio));
            if(!dschon.contains(slotDat)){
                chon.addRow(slotDat.toObject());
                dschon.add(slotDat);
            }else{
                JOptionPane.showMessageDialog(this, "đã đặt slot này");
            }
            
        } catch (ParseException ex) {
            JOptionPane.showMessageDialog(this, "lỗi");
        } catch (ChuaChon ex) {
           JOptionPane.showMessageDialog(this, "chưa chọn");
        } 
    }//GEN-LAST:event_tblSlotMouseClicked

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        int row = tblSlotChon.getSelectedRow();
        if(row < 0 || row >= tblSlotChon.getRowCount()){
            JOptionPane.showMessageDialog(this, "chưa chọn slot");
            return;
        }
        chon.removeRow(row);
        dschon.remove(row);
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnChonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChonActionPerformed
        PhieuDat pd = new PhieuDat();
        pd.setNvDat(nd);
        pd.setNgayDat(new Date());
        pd.setDsSlot(dschon);
        if(dschon.size() > 0){
            (new view.khachhang.TimKhachHangFrm(pd)).setVisible(true);
            this.dispose();
        }else{
            JOptionPane.showMessageDialog(this, "chưa đặt slot nào");
        }
        
    }//GEN-LAST:event_btnChonActionPerformed

    private void btnThuNhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThuNhoActionPerformed
        this.setExtendedState(JFrame.ICONIFIED);
    }//GEN-LAST:event_btnThuNhoActionPerformed

    private void btnThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThoatActionPerformed
        (new view.nguoidung.NhanVienFrm(nd)).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnThoatActionPerformed

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backGround;
    private javax.swing.JButton btnChon;
    private javax.swing.JButton btnThoat;
    private javax.swing.JButton btnThuNho;
    private javax.swing.JButton btnTimKiem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private lu.tudor.santec.jtimechooser.JTimeChooser pkrGioDat;
    private com.toedter.calendar.JDateChooser pkrNgayDat;
    private javax.swing.JTable tblSlot;
    private javax.swing.JTable tblSlotChon;
    private javax.swing.JTextField txtTenDichVu;
    // End of variables declaration//GEN-END:variables
}
