/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.nguoidung;

import java.awt.Color;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import model.NguoiDung;

/**
 *
 * @author My PC
 */
public class ChonLoaiThongKeFrm extends javax.swing.JFrame {

    /**
     * Creates new form ChonLoaiThongKeFrm
     */
    private NguoiDung nd;
    public ChonLoaiThongKeFrm(NguoiDung nd) {
        this.setUndecorated(true);
        initComponents();
        setBackground(new Color(0, 0, 0, 0));
        setLocationRelativeTo(null);
        
        btnQuayLai.setBackground(new Color(0, 0, 0, 0));
        btnThongKeDichVu.setBackground(new Color(0, 0, 0, 0));
        btnThongKeNhanVien.setBackground(new Color(0, 0, 0, 0));
        btnThongkeNguyenLieu.setBackground(new Color(0, 0, 0, 0));
        btnThuNho.setBackground(new Color(0, 0, 0, 0));
        
        this.nd = nd;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnThongKeDichVu = new javax.swing.JButton();
        btnThongkeNguyenLieu = new javax.swing.JButton();
        btnThongKeNhanVien = new javax.swing.JButton();
        btnThuNho = new javax.swing.JButton();
        btnQuayLai = new javax.swing.JButton();
        backGround = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(919, 564));
        getContentPane().setLayout(null);

        btnThongKeDichVu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnThongKeDichVu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThongKeDichVuActionPerformed(evt);
            }
        });
        getContentPane().add(btnThongKeDichVu);
        btnThongKeDichVu.setBounds(264, 174, 391, 66);

        btnThongkeNguyenLieu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnThongkeNguyenLieu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThongkeNguyenLieuActionPerformed(evt);
            }
        });
        getContentPane().add(btnThongkeNguyenLieu);
        btnThongkeNguyenLieu.setBounds(264, 271, 391, 66);

        btnThongKeNhanVien.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnThongKeNhanVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThongKeNhanVienActionPerformed(evt);
            }
        });
        getContentPane().add(btnThongKeNhanVien);
        btnThongKeNhanVien.setBounds(264, 370, 391, 66);

        btnThuNho.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnThuNho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThuNhoActionPerformed(evt);
            }
        });
        getContentPane().add(btnThuNho);
        btnThuNho.setBounds(799, 43, 35, 30);

        btnQuayLai.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnQuayLai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuayLaiActionPerformed(evt);
            }
        });
        getContentPane().add(btnQuayLai);
        btnQuayLai.setBounds(845, 43, 35, 30);

        backGround.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Group 62.png"))); // NOI18N
        getContentPane().add(backGround);
        backGround.setBounds(0, 0, 930, 570);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnThongKeDichVuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThongKeDichVuActionPerformed
        (new view.dichvu.ThongKeDichVuFrm(nd)).setVisible(true);
                    this.dispose();
    }//GEN-LAST:event_btnThongKeDichVuActionPerformed

    private void btnThuNhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThuNhoActionPerformed
        this.setExtendedState(JFrame.ICONIFIED);
    }//GEN-LAST:event_btnThuNhoActionPerformed

    private void btnQuayLaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuayLaiActionPerformed
        (new QuanLyFrm(nd)).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnQuayLaiActionPerformed

    private void btnThongkeNguyenLieuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThongkeNguyenLieuActionPerformed
        JOptionPane.showMessageDialog(this, "chức năng đang được thực hiện!");
    }//GEN-LAST:event_btnThongkeNguyenLieuActionPerformed

    private void btnThongKeNhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThongKeNhanVienActionPerformed
        JOptionPane.showMessageDialog(this, "chức năng đang được thực hiện!");
    }//GEN-LAST:event_btnThongKeNhanVienActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backGround;
    private javax.swing.JButton btnQuayLai;
    private javax.swing.JButton btnThongKeDichVu;
    private javax.swing.JButton btnThongKeNhanVien;
    private javax.swing.JButton btnThongkeNguyenLieu;
    private javax.swing.JButton btnThuNho;
    // End of variables declaration//GEN-END:variables
}
