/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.nguoidung;

import dao.NguoiDungDAO;
import exception.DeTrong;
import java.awt.Color;
import java.nio.file.Files;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import model.NguoiDung;

/**
 *
 * @author My PC
 */
public class DangNhapFrm extends javax.swing.JFrame {

    /**
     * Creates new form DangNhapFrm
     */
    public DangNhapFrm() {
        this.setUndecorated(true);
        initComponents();
        jnoitice.setVisible(false);
        setBackground(new Color(0, 0, 0, 0));
        setLocationRelativeTo(null);
        txtMatKhau.setBackground(new Color(0, 0, 0, 0));
        txtTaiKhoan.setBackground(new Color(0, 0, 0, 0));
        btnThoat.setBackground(new Color(0, 0, 0, 0));
        btnThuNho.setBackground(new Color(0, 0, 0, 0));
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jnoitice = new javax.swing.JLabel();
        txtTaiKhoan = new javax.swing.JTextField();
        txtMatKhau = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnDangNhap = new javax.swing.JButton();
        btnThuNho = new javax.swing.JButton();
        btnThoat = new javax.swing.JButton();
        BG = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(919, 564));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(null);

        jnoitice.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Group 11.png"))); // NOI18N
        getContentPane().add(jnoitice);
        jnoitice.setBounds(620, 460, 140, 30);

        txtTaiKhoan.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        txtTaiKhoan.setForeground(new java.awt.Color(71, 71, 71));
        txtTaiKhoan.setBorder(null);
        txtTaiKhoan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtTaiKhoanKeyPressed(evt);
            }
        });
        getContentPane().add(txtTaiKhoan);
        txtTaiKhoan.setBounds(540, 210, 300, 50);

        txtMatKhau.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        txtMatKhau.setForeground(new java.awt.Color(68, 68, 68));
        txtMatKhau.setBorder(null);
        txtMatKhau.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtMatKhauKeyPressed(evt);
            }
        });
        getContentPane().add(txtMatKhau);
        txtMatKhau.setBounds(540, 290, 300, 50);

        jLabel1.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(188, 188, 188));
        jLabel1.setText("Mật khẩu");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(630, 290, 110, 40);

        jLabel2.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(188, 188, 188));
        jLabel2.setText("Tài khoản");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(630, 220, 105, 30);

        btnDangNhap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Group 2.png"))); // NOI18N
        btnDangNhap.setBorder(null);
        btnDangNhap.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDangNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDangNhapActionPerformed(evt);
            }
        });
        getContentPane().add(btnDangNhap);
        btnDangNhap.setBounds(580, 370, 220, 80);

        btnThuNho.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnThuNho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThuNhoActionPerformed(evt);
            }
        });
        getContentPane().add(btnThuNho);
        btnThuNho.setBounds(800, 40, 30, 30);

        btnThoat.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThoatActionPerformed(evt);
            }
        });
        getContentPane().add(btnThoat);
        btnThoat.setBounds(850, 40, 30, 30);

        BG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Group 12.png"))); // NOI18N
        getContentPane().add(BG);
        BG.setBounds(0, 0, 930, 570);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDangNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDangNhapActionPerformed
        try {
            NguoiDung nd = new NguoiDung();
            String tk = txtTaiKhoan.getText();
            String mk = txtMatKhau.getText();
            if(tk.length() == 0 || mk.length() == 0) throw new exception.DeTrong();
            nd.setTenDangNhap(tk);
            nd.setMatKhau(mk);
            
            NguoiDungDAO ndDAO = new NguoiDungDAO();
            if(ndDAO.kiemTraDangNhap(nd)) {
                if(nd.getViTri().equalsIgnoreCase("quanly")) {
                    (new QuanLyFrm(nd)).setVisible(true);
                    
                    this.dispose();
                }else if(nd.getViTri().equalsIgnoreCase("nhanvien")) {
                    (new NhanVienFrm(nd)).setVisible(true);
                    this.dispose();
                }else
                    JOptionPane.showMessageDialog(this, "Chức năng đang hoàn thành");
            }else {
                jnoitice.setVisible(true);
            }
        } catch (DeTrong ex) {
            jnoitice.setVisible(true);
        }
       
       
    }//GEN-LAST:event_btnDangNhapActionPerformed

    private void txtMatKhauKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMatKhauKeyPressed
        jLabel1.setVisible(false);
    }//GEN-LAST:event_txtMatKhauKeyPressed

    private void txtTaiKhoanKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTaiKhoanKeyPressed
        jLabel2.setVisible(false);
    }//GEN-LAST:event_txtTaiKhoanKeyPressed

    private void btnThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThoatActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnThoatActionPerformed

    private void btnThuNhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThuNhoActionPerformed
        this.setExtendedState(JFrame.ICONIFIED);
    }//GEN-LAST:event_btnThuNhoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        //jnoitice.setVisible(false);
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DangNhapFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DangNhapFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DangNhapFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DangNhapFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DangNhapFrm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BG;
    private javax.swing.JButton btnDangNhap;
    private javax.swing.JButton btnThoat;
    private javax.swing.JButton btnThuNho;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jnoitice;
    private javax.swing.JPasswordField txtMatKhau;
    private javax.swing.JTextField txtTaiKhoan;
    // End of variables declaration//GEN-END:variables
}
