/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.phieudat;

import dao.PhieuDatDAO;
import java.awt.Color;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;
import model.PhieuDat;
import model.ThongKeDichVu;
import view.dichvu.ThongKeDichVuFrm;

/**
 *
 * @author My PC
 */
public class DSHoaDonFrm extends javax.swing.JFrame {

    /**
     * Creates new form DSHoaDonFrm
     */
    private ThongKeDichVu tkdv;
        
    private DefaultTableModel bang;
    private ArrayList <PhieuDat> dspd;
    private ThongKeDichVuFrm formthongke;
    public DSHoaDonFrm(ThongKeDichVuFrm formthongke,ThongKeDichVu tkdv, Date ngaybd, Date ngaykt) {
        initComponents();
        this.setUndecorated(true);setBackground(new Color(0, 0, 0, 0));
        this.setLocationRelativeTo(null);
        this.formthongke = formthongke;
        this.tkdv = tkdv;
        btnQuayLai.setBackground(new Color(0, 0, 0, 0));
        btnThuNho.setBackground(new Color(0, 0, 0, 0));
        bang = (DefaultTableModel) tbldsHoaDon.getModel();
        PhieuDatDAO pdDAO = new PhieuDatDAO();
        dspd = pdDAO.DSPhieuDatTheoDichVu(tkdv.getMa(), ngaybd, ngaykt);
        
        for( PhieuDat pd: dspd)
            bang.addRow(pd.toObject());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbldsHoaDon = new javax.swing.JTable();
        btnQuayLai = new javax.swing.JButton();
        btnThuNho = new javax.swing.JButton();
        backGround = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1320, 724));
        getContentPane().setLayout(null);

        tbldsHoaDon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã phiếu", "Tên khách", "Số điện thoại", "Ngày đăt"
            }
        ));
        tbldsHoaDon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbldsHoaDonMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbldsHoaDon);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(90, 140, 1180, 520);

        btnQuayLai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuayLaiActionPerformed(evt);
            }
        });
        getContentPane().add(btnQuayLai);
        btnQuayLai.setBounds(1237, 40, 40, 40);

        btnThuNho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThuNhoActionPerformed(evt);
            }
        });
        getContentPane().add(btnThuNho);
        btnThuNho.setBounds(1180, 40, 40, 40);

        backGround.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Group 57.png"))); // NOI18N
        getContentPane().add(backGround);
        backGround.setBounds(0, 0, 1330, 720);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnQuayLaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuayLaiActionPerformed
        this.dispose();
        this.formthongke.setVisible(true);
    }//GEN-LAST:event_btnQuayLaiActionPerformed

    private void tbldsHoaDonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbldsHoaDonMouseClicked
        int row = tbldsHoaDon.getSelectedRow();
        if(row < 0 || row >= tbldsHoaDon.getRowCount())
            return;
        new view.phieudat.HoaDonChiTietFrm(this,new PhieuDatDAO().getPhieuDat(dspd.get(row).getMa())).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_tbldsHoaDonMouseClicked

    private void btnThuNhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThuNhoActionPerformed
        this.setExtendedState(JFrame.ICONIFIED);
    }//GEN-LAST:event_btnThuNhoActionPerformed

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backGround;
    private javax.swing.JButton btnQuayLai;
    private javax.swing.JButton btnThuNho;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbldsHoaDon;
    // End of variables declaration//GEN-END:variables
}
