/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.phieudat;

import java.awt.Color;
import javax.swing.table.DefaultTableModel;
import model.DichVuDung;
import model.NguyenLieuDung;
import model.PhieuDat;
import model.SlotDat;

/**
 *
 * @author My PC
 */
public class HoaDonChiTietFrm extends javax.swing.JFrame {

    /**
     * Creates new form HoaDonChiTietFrm
     */
    private DSHoaDonFrm form;
    private PhieuDat pd;
    private DefaultTableModel bang;
    public HoaDonChiTietFrm(DSHoaDonFrm form,PhieuDat pd) {
        initComponents();
        this.setUndecorated(true);setBackground(new Color(0, 0, 0, 0));
        this.setLocationRelativeTo(null);
        this.pd = pd;
        this.form = form;
        btnQuayLai.setBackground(new Color(0, 0, 0, 0));
        btnThuNho.setBackground(new Color(0, 0, 0, 0));
        txtSDT.setBackground(new Color(0, 0, 0, 0));
        txtSoSlot.setBackground(new Color(0, 0, 0, 0));
        txtTenKhach.setBackground(new Color(0, 0, 0, 0));
        txtTongTien.setBackground(new Color(0, 0, 0, 0));
        btnXong.setBackground(new Color(0, 0, 0, 0));
        
        txtTenKhach.setText(pd.getKh().getTen());
        txtSDT.setText(String.valueOf(pd.getKh().getSoDienThoai()));
        txtSoSlot.setText(String.valueOf(pd.getDsSlot().size()));
        bang = (DefaultTableModel) tblDanhSach.getModel();
        
        
        //float tongTien = 0;
        for(SlotDat slot: pd.getDsSlot()){
            for(DichVuDung dv: slot.getDsdv()){
                bang.addRow(dv.toObject());
              //  tongTien += dv.getGia();
            }
                
        }
        
        while(bang.getRowCount() > 0)
                bang.removeRow(0);
        
        for(SlotDat slot: pd.getDsSlot()){
            for(NguyenLieuDung nl: slot.getDsnl()){
                bang.addRow(nl.toObject());
               // tongTien += nl.tinhTien();
            }
                
        }
        
        txtTongTien.setText(String.valueOf(pd.tinhTien()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtTenKhach = new javax.swing.JTextField();
        txtSDT = new javax.swing.JTextField();
        txtSoSlot = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDanhSach = new javax.swing.JTable();
        btnXong = new javax.swing.JButton();
        txtTongTien = new javax.swing.JTextField();
        btnQuayLai = new javax.swing.JButton();
        btnThuNho = new javax.swing.JButton();
        backGround = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1320, 724));
        getContentPane().setLayout(null);

        txtTenKhach.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        txtTenKhach.setEnabled(false);
        getContentPane().add(txtTenKhach);
        txtTenKhach.setBounds(610, 140, 200, 40);

        txtSDT.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        txtSDT.setEnabled(false);
        getContentPane().add(txtSDT);
        txtSDT.setBounds(980, 140, 40, 40);

        txtSoSlot.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        txtSoSlot.setEnabled(false);
        getContentPane().add(txtSoSlot);
        txtSoSlot.setBounds(230, 140, 150, 40);

        tblDanhSach.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        tblDanhSach.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tên ", "Giá", "Khuyến mại", "Số lượng", "Thành tiền"
            }
        ));
        jScrollPane1.setViewportView(tblDanhSach);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(50, 210, 1220, 402);

        btnXong.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        btnXong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXongActionPerformed(evt);
            }
        });
        getContentPane().add(btnXong);
        btnXong.setBounds(1060, 130, 140, 50);

        txtTongTien.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        txtTongTien.setEnabled(false);
        getContentPane().add(txtTongTien);
        txtTongTien.setBounds(1020, 630, 220, 40);
        getContentPane().add(btnQuayLai);
        btnQuayLai.setBounds(1240, 40, 40, 40);
        getContentPane().add(btnThuNho);
        btnThuNho.setBounds(1180, 40, 40, 40);

        backGround.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Group 72.png"))); // NOI18N
        getContentPane().add(backGround);
        backGround.setBounds(0, 0, 1320, 724);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnXongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXongActionPerformed
        this.form.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnXongActionPerformed

   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backGround;
    private javax.swing.JButton btnQuayLai;
    private javax.swing.JButton btnThuNho;
    private javax.swing.JButton btnXong;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblDanhSach;
    private javax.swing.JTextField txtSDT;
    private javax.swing.JTextField txtSoSlot;
    private javax.swing.JTextField txtTenKhach;
    private javax.swing.JTextField txtTongTien;
    // End of variables declaration//GEN-END:variables
}
