/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.phieudat;

import dao.PhieuDatDAO;
import exception.ChonSai;
import exception.DeTrong;
import java.awt.Color;
import java.awt.Font;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.NguoiDung;
import model.PhieuDat;
import view.nguoidung.NhanVienFrm;

/**
 *
 * @author My PC
 */
public class TimPhieuThanhToanFrm extends javax.swing.JFrame {

    private ArrayList <PhieuDat> dspd;
    private DefaultTableModel bang;
    private NguoiDung nd;
    public TimPhieuThanhToanFrm( NguoiDung nd) {
        this.setUndecorated(true);
        initComponents();
        setBackground(new Color(0, 0, 0, 0));
        setLocationRelativeTo(null);
        
        txtTenKhachHang.setBackground(new Color(0, 0, 0, 0));
        btnQuayLai.setBackground(new Color(0, 0, 0, 0));
        btnThuNho.setBackground(new Color(0, 0, 0, 0));
        btnTimKiem.setBackground(new Color(0, 0, 0, 0));
        
        tblKhachHang.getTableHeader().setFont(new Font("Arial", 1 , 18));
        this.nd = nd;
        bang = (DefaultTableModel) tblKhachHang.getModel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnTimKiem = new javax.swing.JButton();
        btnThuNho = new javax.swing.JButton();
        btnQuayLai = new javax.swing.JButton();
        txtTenKhachHang = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblKhachHang = new javax.swing.JTable();
        backGround = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1320, 725));
        getContentPane().setLayout(null);

        btnTimKiem.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnTimKiem.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnTimKiem.setFocusCycleRoot(true);
        btnTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiemActionPerformed(evt);
            }
        });
        getContentPane().add(btnTimKiem);
        btnTimKiem.setBounds(985, 109, 166, 63);

        btnThuNho.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnThuNho.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnThuNho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThuNhoActionPerformed(evt);
            }
        });
        getContentPane().add(btnThuNho);
        btnThuNho.setBounds(1180, 30, 40, 40);

        btnQuayLai.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnQuayLai.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnQuayLai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuayLaiActionPerformed(evt);
            }
        });
        getContentPane().add(btnQuayLai);
        btnQuayLai.setBounds(1240, 30, 40, 40);

        txtTenKhachHang.setFont(new java.awt.Font("Arial", 0, 30)); // NOI18N
        txtTenKhachHang.setBorder(null);
        getContentPane().add(txtTenKhachHang);
        txtTenKhachHang.setBounds(610, 118, 350, 46);

        tblKhachHang.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        tblKhachHang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã phiếu", "Tên khách", "Số điện thoại", "Ngày đặt", "Tình trạng"
            }
        ));
        tblKhachHang.setRowHeight(24);
        tblKhachHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblKhachHangMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblKhachHang);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(290, 200, 970, 460);

        backGround.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Group 41.png"))); // NOI18N
        getContentPane().add(backGround);
        backGround.setBounds(0, 0, 1320, 710);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiemActionPerformed
        try {
            PhieuDatDAO pdDAO = new PhieuDatDAO();
            String ten = txtTenKhachHang.getText().trim();
            if(ten.length() == 0) throw new exception.DeTrong();
            dspd = new PhieuDatDAO().timPhieuDat(ten);
            
            while(bang.getRowCount() > 0)
                bang.removeRow(0);
            
            ArrayList <PhieuDat> xoa = new ArrayList<PhieuDat>();
            for( int i = 0; i < dspd.size(); i++){
                System.out.println("i :" + i);
                if(dspd.get(i).getGhiChu().equals("Chưa thanh toán"))
                bang.addRow(dspd.get(i).toObject());
                else
                    xoa.add(dspd.get(i));
            }
            
            for(PhieuDat x: xoa){
                dspd.remove(x);
            }
                
          
                
        } catch (DeTrong ex) {
            JOptionPane.showMessageDialog(this, "Chưa nhập tên khách");
        }
           
    }//GEN-LAST:event_btnTimKiemActionPerformed

    private void tblKhachHangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblKhachHangMouseClicked
        try {
            int row = tblKhachHang.getSelectedRow();
            if(row < 0 || row >= tblKhachHang.getRowCount()){
                JOptionPane.showMessageDialog(this, "Chưa chọn phiếu");
                return;
            }
            
            PhieuDat pd = dspd.get(row);
            if(pd.getGhiChu().equals("da thanh toan")) throw new exception.ChonSai();
            pd.setNvThanhToan(nd);
            pd.setNgayThanhToan(new Date());
            (new view.phieudat.HoaDonFrm(pd)).setVisible(true);
            this.dispose();
        } catch (ChonSai ex) {
            JOptionPane.showMessageDialog(this, "Phiếu này đã được thanh toán");
        }
    }//GEN-LAST:event_tblKhachHangMouseClicked

    private void btnQuayLaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuayLaiActionPerformed
        (new NhanVienFrm(nd)).setVisible(true);
                    this.dispose();
    }//GEN-LAST:event_btnQuayLaiActionPerformed

    private void btnThuNhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThuNhoActionPerformed
        this.setExtendedState(JFrame.ICONIFIED);
    }//GEN-LAST:event_btnThuNhoActionPerformed

   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backGround;
    private javax.swing.JButton btnQuayLai;
    private javax.swing.JButton btnThuNho;
    private javax.swing.JButton btnTimKiem;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblKhachHang;
    private javax.swing.JTextField txtTenKhachHang;
    // End of variables declaration//GEN-END:variables
}
