/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.khachhang;

import dao.KhachHangDAO;
import exception.DeTrong;
import java.awt.Color;
import java.awt.Font;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.KhachHang;
import model.NguoiDung;
import model.PhieuDat;
import model.Slot;
import model.SlotDat;

/**
 *
 * @author My PC
 */
public class TimKhachHangFrm extends javax.swing.JFrame {

    private PhieuDat pd;
    private ArrayList <KhachHang> dskh;
    private DefaultTableModel bang;
    //NguoiDung nd;

    public TimKhachHangFrm(PhieuDat pd) {
        this.setUndecorated(true);
        initComponents();
        setBackground(new Color(0, 0, 0, 0));
        setLocationRelativeTo(null);
        
        txtDiaChi.setBackground(new Color(0, 0, 0, 0));
        txtEmail.setBackground(new Color(0, 0, 0, 0));
        txtSoDienThoai.setBackground(new Color(0, 0, 0, 0));
        txtTen.setBackground(new Color(0, 0, 0, 0));
        btnThem.setBackground(new Color(0, 0, 0, 0));
        btnThoat.setBackground(new Color(0, 0, 0, 0));
        btnTimKiem.setBackground(new Color(0, 0, 0, 0));
        btnThuNho.setBackground(new Color(0, 0, 0, 0));
        
        tblDanhSachKhachHang.getTableHeader().setBackground(new Color(0, 0, 0));
        tblDanhSachKhachHang.getTableHeader().setFont(new Font("Arial", 1 , 20));
        
        this.pd = pd;
        bang = (DefaultTableModel) tblDanhSachKhachHang.getModel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnTimKiem = new javax.swing.JButton();
        btnThem = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDanhSachKhachHang = new javax.swing.JTable();
        txtSoDienThoai = new javax.swing.JTextField();
        txtTen = new javax.swing.JTextField();
        txtDiaChi = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        btnThoat = new javax.swing.JButton();
        btnThuNho = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(919, 564));
        setPreferredSize(new java.awt.Dimension(1320, 724));
        getContentPane().setLayout(null);

        btnTimKiem.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiemActionPerformed(evt);
            }
        });
        getContentPane().add(btnTimKiem);
        btnTimKiem.setBounds(283, 590, 172, 63);

        btnThem.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });
        getContentPane().add(btnThem);
        btnThem.setBounds(480, 590, 150, 63);

        tblDanhSachKhachHang.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        tblDanhSachKhachHang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã", "Tên", "Địa chỉ", "Email", "Số điện thoại", "Ghi chú"
            }
        ));
        tblDanhSachKhachHang.setRowHeight(27);
        tblDanhSachKhachHang.setSelectionBackground(new java.awt.Color(0, 153, 102));
        tblDanhSachKhachHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDanhSachKhachHangMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblDanhSachKhachHang);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(640, 120, 640, 540);

        txtSoDienThoai.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        txtSoDienThoai.setForeground(new java.awt.Color(255, 255, 255));
        txtSoDienThoai.setBorder(null);
        getContentPane().add(txtSoDienThoai);
        txtSoDienThoai.setBounds(310, 287, 220, 50);

        txtTen.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        txtTen.setForeground(new java.awt.Color(255, 255, 255));
        txtTen.setBorder(null);
        getContentPane().add(txtTen);
        txtTen.setBounds(310, 176, 200, 50);

        txtDiaChi.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        txtDiaChi.setForeground(new java.awt.Color(255, 255, 255));
        txtDiaChi.setBorder(null);
        getContentPane().add(txtDiaChi);
        txtDiaChi.setBounds(310, 508, 260, 51);

        txtEmail.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        txtEmail.setForeground(new java.awt.Color(255, 255, 255));
        txtEmail.setBorder(null);
        getContentPane().add(txtEmail);
        txtEmail.setBounds(310, 397, 240, 51);

        btnThoat.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThoatActionPerformed(evt);
            }
        });
        getContentPane().add(btnThoat);
        btnThoat.setBounds(1235, 40, 40, 40);

        btnThuNho.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnThuNho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThuNhoActionPerformed(evt);
            }
        });
        getContentPane().add(btnThuNho);
        btnThuNho.setBounds(1170, 40, 40, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Group 21.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1320, 724);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiemActionPerformed
        
        try {
            KhachHangDAO khDAO = new KhachHangDAO();
            String ten = txtTen.getText();
            ten = ten.trim();
            if(ten.length() == 0) throw new exception.DeTrong();
            dskh = khDAO.timKhachHang(ten);
            
            while(bang.getRowCount() > 0)
                bang.removeRow(0);
            
            for (KhachHang k : dskh){
                bang.addRow(k.toObject());
                //System.out.println(sl);
            }
        } catch (DeTrong ex) {
            JOptionPane.showMessageDialog(this, "chưa nhập tên khách");
        }
        
    }//GEN-LAST:event_btnTimKiemActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        try {
            KhachHang kh = new KhachHang();
            String ten  = txtTen.getText();
            String dc = txtDiaChi.getText();
            String email = txtEmail.getText();
            int sdt = Integer.parseInt(txtSoDienThoai.getText());
            ten = ten.trim();
            dc = dc.trim();
            email = email.trim();
            if(ten.length() == 0 || dc.length() == 0 || email.length() == 0) throw new exception.DeTrong();
            kh.setTen(ten);
            kh.setDiaChi(dc);
            kh.setEmail(email);
            kh.setSoDienThoai(sdt);
            kh.setGhichu(" ");

            KhachHangDAO khDAO = new KhachHangDAO();
            if(khDAO.themKhachHang(kh)){
                JOptionPane.showMessageDialog(this, "thêm thành công");
                pd.setKh(kh);
                //if(pd.getDsSlot().size() > 0){
                    (new view.phieudat.XacNhanFrm(pd)).setVisible(true);

                        this.dispose();
//                }else{
//                    JOptionPane.showMessageDialog(this, "Chưa chọn slot");
//                    return;
//                }
            }
            else
                JOptionPane.showMessageDialog(this, "thêm không thành công");
        } catch (DeTrong ex) {
            JOptionPane.showMessageDialog(this, "chưa nhập đủ thông tin");
        }catch(NumberFormatException ex){
            JOptionPane.showMessageDialog(this, "nhập sai số điện thoại");
        }
        
    }//GEN-LAST:event_btnThemActionPerformed

    private void tblDanhSachKhachHangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDanhSachKhachHangMouseClicked
       int row = tblDanhSachKhachHang.getSelectedRow();
    if(row < 0 || row >= tblDanhSachKhachHang.getRowCount())
        return;
    
    pd.setKh(dskh.get(row));
    (new view.phieudat.XacNhanFrm(pd)).setVisible(true);
    this.dispose();

        
    }//GEN-LAST:event_tblDanhSachKhachHangMouseClicked

    private void btnThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThoatActionPerformed
        (new view.slot.TimSlotFrm(pd.getNvDat())).setVisible(true);
        
        this.dispose();
        
    }//GEN-LAST:event_btnThoatActionPerformed

    private void btnThuNhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThuNhoActionPerformed
        this.setExtendedState(JFrame.ICONIFIED);
    }//GEN-LAST:event_btnThuNhoActionPerformed

 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnThoat;
    private javax.swing.JButton btnThuNho;
    private javax.swing.JButton btnTimKiem;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblDanhSachKhachHang;
    private javax.swing.JTextField txtDiaChi;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtSoDienThoai;
    private javax.swing.JTextField txtTen;
    // End of variables declaration//GEN-END:variables

}