/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.nhanvien;

import dao.NVDichVuDAO;
import java.awt.Color;
import java.awt.Font;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.CongLam;
import model.DichVuChiTiet;
import model.DichVuDung;
import model.NVDichVu;
import view.dichvu.TimDichVuChiTietFrm;
import view.slot.NhapThongTinSlotDatFrm;

/**
 *
 * @author My PC
 */
public class TimNhanVienDVFrm extends javax.swing.JFrame {

    /**
     * Creates new form TimNhanVienDVFrm
     */
    private DichVuDung dvd;
    private ArrayList <CongLam> cl;
    private TimDichVuChiTietFrm fromnhap;
    private ArrayList <NVDichVu> dsnv;
    private DefaultTableModel bang;
    private int X,Y;
    
    public TimNhanVienDVFrm(DichVuDung dvd, TimDichVuChiTietFrm fromnhap) {
        this.setUndecorated(true);
        initComponents();
        setBackground(new Color(0, 0, 0, 0));
        setLocationRelativeTo(null);
        
        tblNhanVienDichVu.getTableHeader().setBackground(new Color(0, 0, 0));
        tblNhanVienDichVu.getTableHeader().setFont(new Font("Arial", 1 , 22));
        
        btnThem.setBackground(new Color(0, 0, 0, 0));
        btnXacNhan.setBackground(new Color(0, 0, 0, 0));
        
        this.fromnhap = fromnhap;
        this.dvd = dvd;
        cl = new ArrayList<>();
        NVDichVuDAO nvDAO = new NVDichVuDAO ();
        dsnv = nvDAO.timNhanVien(dvd.getDv().getMa(), fromnhap.getFormnhap().getSlot().getNgayGio());
        bang = (DefaultTableModel) tblNhanVienDichVu.getModel();
        for( NVDichVu nv: dsnv)
            bang.addRow(nv.toObject());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblNhanVienDichVu = new javax.swing.JTable();
        btnThem = new javax.swing.JButton();
        btnXacNhan = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(860, 610));
        getContentPane().setLayout(null);

        tblNhanVienDichVu.setFont(new java.awt.Font("Arial", 0, 22)); // NOI18N
        tblNhanVienDichVu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã", "Tên", "Ca làm"
            }
        ));
        tblNhanVienDichVu.setRowHeight(24);
        jScrollPane1.setViewportView(tblNhanVienDichVu);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(60, 90, 740, 430);

        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });
        getContentPane().add(btnThem);
        btnThem.setBounds(320, 550, 110, 40);

        btnXacNhan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXacNhanActionPerformed(evt);
            }
        });
        getContentPane().add(btnXacNhan);
        btnXacNhan.setBounds(440, 550, 110, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Group 70.png"))); // NOI18N
        jLabel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabel1MouseDragged(evt);
            }
        });
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel1MousePressed(evt);
            }
        });
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 860, 610);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        int row = tblNhanVienDichVu.getSelectedRow();
        if(row < 0 || row >= tblNhanVienDichVu.getRowCount()){
            JOptionPane.showMessageDialog(this, "Chưa chọn nhân viên");
            return;
        }
            
        NVDichVu nv = dsnv.get(row);
        CongLam cong = new CongLam();
        cong.setNv(nv);
        JOptionPane.showMessageDialog(this, "thêm nhân viên:  \n "
                + "Mã nhân viên: "+ nv.getMa()+ "\n"+ "Tên nhân viên: " + nv.getTen());
        cong.setNgaygio(fromnhap.getFormnhap().getSlot().getNgayGio());
        cl.add(cong);
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnXacNhanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXacNhanActionPerformed
        System.out.println("sze :" + cl.size() );
        if(cl.size() > 0){
            dvd.setDscong(cl);
            this.dispose();
        }else{
            JOptionPane.showMessageDialog(this, "Chưa chọn nhân viên");
        }
        
    }//GEN-LAST:event_btnXacNhanActionPerformed

    private void jLabel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MousePressed
        X = evt.getX();
        Y = evt.getY();
    }//GEN-LAST:event_jLabel1MousePressed

    private void jLabel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseDragged
        this.setLocation((evt.getX()+this.getX())-X,( evt.getY()+this.getY())-Y);
    }//GEN-LAST:event_jLabel1MouseDragged

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnXacNhan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblNhanVienDichVu;
    // End of variables declaration//GEN-END:variables
}
