/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.dichvu;

import dao.ThongKeDichVuDAO;
import exception.SaiNgay;
import java.awt.Color;
import java.awt.Font;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import model.NguoiDung;
import model.ThongKeDichVu;
import view.nguoidung.ChonLoaiThongKeFrm;
import view.nguoidung.QuanLyFrm;

/**
 *
 * @author My PC
 */
public class ThongKeDichVuFrm extends javax.swing.JFrame {

    /**
     * Creates new form ThongKeDichVuFrm
     */
    private NguoiDung nd;
    private ArrayList <ThongKeDichVu> dstk;
    private DefaultTableModel bang;
    private Date ngaybd;
    private Date ngaykt;
   
    public ThongKeDichVuFrm(NguoiDung nd) {
        this.setUndecorated(true);
        initComponents();
        setBackground(new Color(0, 0, 0, 0));
        setLocationRelativeTo(null);
        
        JTextField a = (JTextField) txtNgayBatDau.getComponent(1); a.setEditable(false);
        JTextField b = (JTextField) txtNgayKetThuc.getComponent(1); b.setEditable(false);
        
        btnQuayLai.setBackground(new Color(0, 0, 0, 0));
        btnThongKe.setBackground(new Color(0, 0, 0, 0));
        btnThuNho.setBackground(new Color(0, 0, 0, 0));
        txtNgayBatDau.setBackground(new Color(0, 0, 0, 0));
        txtNgayKetThuc.setBackground(new Color(0, 0, 0, 0));
        JTableHeader header = tblThongKeDichVu.getTableHeader();
        
        tblThongKeDichVu.getTableHeader().setOpaque(false);
        tblThongKeDichVu.getTableHeader().setBackground(new Color(32,136,201));
        tblThongKeDichVu.getTableHeader().setFont(new Font("Arial", 1 , 18));
        this.nd = nd;
        dstk = new ArrayList<>();
        bang = (DefaultTableModel) tblThongKeDichVu.getModel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtNgayKetThuc = new com.toedter.calendar.JDateChooser();
        txtNgayBatDau = new com.toedter.calendar.JDateChooser();
        btnThongKe = new javax.swing.JButton();
        btnQuayLai = new javax.swing.JButton();
        btnThuNho = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblThongKeDichVu = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1320, 724));
        getContentPane().setLayout(null);

        txtNgayKetThuc.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        getContentPane().add(txtNgayKetThuc);
        txtNgayKetThuc.setBounds(780, 130, 290, 40);

        txtNgayBatDau.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        getContentPane().add(txtNgayBatDau);
        txtNgayBatDau.setBounds(240, 130, 310, 40);

        btnThongKe.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnThongKe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThongKeActionPerformed(evt);
            }
        });
        getContentPane().add(btnThongKe);
        btnThongKe.setBounds(1110, 120, 140, 60);

        btnQuayLai.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnQuayLai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuayLaiActionPerformed(evt);
            }
        });
        getContentPane().add(btnQuayLai);
        btnQuayLai.setBounds(1240, 50, 40, 30);

        btnThuNho.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnThuNho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThuNhoActionPerformed(evt);
            }
        });
        getContentPane().add(btnThuNho);
        btnThuNho.setBounds(1180, 50, 40, 30);

        tblThongKeDichVu.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        tblThongKeDichVu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã", "Tên dịch vụ", "Mô tả", "Doanh thu", "So luong"
            }
        ));
        tblThongKeDichVu.setRowHeight(34);
        tblThongKeDichVu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblThongKeDichVuMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblThongKeDichVu);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(80, 220, 1170, 440);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Group 58.png"))); // NOI18N
        jLabel1.setPreferredSize(null);
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1320, 730);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnThongKeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThongKeActionPerformed

        try {
             ngaybd = txtNgayBatDau.getDate();
             
            ngaykt = txtNgayKetThuc.getDate();
           
            if( ngaybd.getTime() > ngaykt.getTime())  throw new exception.SaiNgay();
                //loi ngay bd lon hon ngay kthuc
            ThongKeDichVuDAO tkDAO = new ThongKeDichVuDAO();
            
            while(bang.getRowCount() > 0)
                bang.removeRow(0);
            dstk = tkDAO.getTKDichVu(ngaybd, ngaykt);
            for(ThongKeDichVu tkdv: dstk)
                bang.addRow(tkdv.toObject());
        }  catch (SaiNgay ex) {
            JOptionPane.showMessageDialog(this, "ngày bắt đầu < ngày kết thúc ");
        }
    }//GEN-LAST:event_btnThongKeActionPerformed

    private void tblThongKeDichVuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblThongKeDichVuMouseClicked
        int row = tblThongKeDichVu.getSelectedRow();
            if(row < 0 || row >= tblThongKeDichVu.getRowCount())
                return;
         
        try {
            
            if( ngaybd.getTime() > ngaykt.getTime()) throw new exception.SaiNgay();
                //loi ngay bd lon hon ngay kthuc
            (new view.phieudat.DSHoaDonFrm(this,dstk.get(row), ngaybd, ngaykt )).setVisible(true);
                        this.setVisible(false);
        } catch (SaiNgay ex) {
            JOptionPane.showMessageDialog(this, "ngày bắt đầu < ngày kết thúc ");
        }
            
            
    }//GEN-LAST:event_tblThongKeDichVuMouseClicked

    private void btnThuNhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThuNhoActionPerformed
        this.setExtendedState(JFrame.ICONIFIED);
    }//GEN-LAST:event_btnThuNhoActionPerformed

    private void btnQuayLaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuayLaiActionPerformed
        (new ChonLoaiThongKeFrm(nd)).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnQuayLaiActionPerformed

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnQuayLai;
    private javax.swing.JButton btnThongKe;
    private javax.swing.JButton btnThuNho;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblThongKeDichVu;
    private com.toedter.calendar.JDateChooser txtNgayBatDau;
    private com.toedter.calendar.JDateChooser txtNgayKetThuc;
    // End of variables declaration//GEN-END:variables
}
