/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.nguyenlieu;

import dao.NguyenLieuDAO;
import dao.NguyenLieuDungDAO;
import exception.ChuaChon;
import exception.DeTrong;
import exception.SaiPhanTram;
import exception.SaiSo;
import java.awt.Color;
import java.awt.Font;
import java.awt.Point;
import java.awt.event.MouseMotionListener;
import java.util.ArrayList;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.NguyenLieu;
import model.NguyenLieuDung;
import view.slot.ChiTietSlotDatFrm;

/**
 *
 * @author My PC
 */
public class ThemNguyenLieuDungFrm extends javax.swing.JFrame {

    /**
     * Creates new form ThemNguyenLieuDungFrm
     */
    private ArrayList <NguyenLieu> dsnl;
    private DefaultTableModel bang;
    private ChiTietSlotDatFrm gdchitiet;
    
    private int X,Y;
    public ThemNguyenLieuDungFrm(ChiTietSlotDatFrm gdchitiet) {
        this.setUndecorated(true);
        initComponents();
        setBackground(new Color(0, 0, 0, 0));
        
        btnThem.setBackground(new Color(0, 0, 0, 0));
        btnTimKiem.setBackground(new Color(0, 0, 0, 0));
        btnXong.setBackground(new Color(0, 0, 0, 0));
        txtSoLuong.setBackground(new Color(0, 0, 0, 0));
        txtTenNguyenLieu.setBackground(new Color(0, 0, 0, 0));
        txtKhuyenMai.setBackground(new Color(0, 0, 0, 0));
        
        tblDanhSachNguyenLieu.getTableHeader().setFont(new Font("Arial", 1 , 18));
        this.gdchitiet = gdchitiet;
        bang = (DefaultTableModel) tblDanhSachNguyenLieu.getModel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtTenNguyenLieu = new javax.swing.JTextField();
        btnTimKiem = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDanhSachNguyenLieu = new javax.swing.JTable();
        txtSoLuong = new javax.swing.JTextField();
        txtKhuyenMai = new javax.swing.JTextField();
        btnThem = new javax.swing.JButton();
        btnXong = new javax.swing.JButton();
        backGround = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(0, 0));
        setMinimumSize(new java.awt.Dimension(723, 663));
        setType(java.awt.Window.Type.POPUP);
        getContentPane().setLayout(null);

        txtTenNguyenLieu.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        txtTenNguyenLieu.setBorder(null);
        getContentPane().add(txtTenNguyenLieu);
        txtTenNguyenLieu.setBounds(236, 113, 230, 36);

        btnTimKiem.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnTimKiem.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiemActionPerformed(evt);
            }
        });
        getContentPane().add(btnTimKiem);
        btnTimKiem.setBounds(476, 114, 123, 35);

        tblDanhSachNguyenLieu.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        tblDanhSachNguyenLieu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã", "Tên", "Đơn vị", "Dung tích", "Giá"
            }
        ));
        tblDanhSachNguyenLieu.setRowHeight(24);
        jScrollPane1.setViewportView(tblDanhSachNguyenLieu);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(40, 160, 640, 340);

        txtSoLuong.setFont(new java.awt.Font("Arial", 0, 28)); // NOI18N
        txtSoLuong.setAutoscrolls(false);
        txtSoLuong.setBorder(null);
        txtSoLuong.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        getContentPane().add(txtSoLuong);
        txtSoLuong.setBounds(240, 512, 220, 32);

        txtKhuyenMai.setFont(new java.awt.Font("Arial", 0, 28)); // NOI18N
        txtKhuyenMai.setAutoscrolls(false);
        txtKhuyenMai.setBorder(null);
        txtKhuyenMai.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        getContentPane().add(txtKhuyenMai);
        txtKhuyenMai.setBounds(240, 560, 220, 32);

        btnThem.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnThem.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });
        getContentPane().add(btnThem);
        btnThem.setBounds(504, 514, 100, 35);

        btnXong.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnXong.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnXong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXongActionPerformed(evt);
            }
        });
        getContentPane().add(btnXong);
        btnXong.setBounds(504, 558, 100, 35);

        backGround.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Group 55.png"))); // NOI18N
        backGround.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                backGroundMouseDragged(evt);
            }
        });
        backGround.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                backGroundMousePressed(evt);
            }
        });
        getContentPane().add(backGround);
        backGround.setBounds(0, 0, 723, 663);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiemActionPerformed
        try {
            NguyenLieuDAO nlDAO = new NguyenLieuDAO();
            String ten = txtTenNguyenLieu.getText();
            ten = ten.trim();
            if(ten.length() == 0) throw new exception.DeTrong();
            dsnl = nlDAO.timNguyenLieu(ten);
            
            while(bang.getRowCount() > 0)
                bang.removeRow(0);
            for(NguyenLieu nl: dsnl)
                bang.addRow(nl.toObject());
        } catch (DeTrong ex) {
            JOptionPane.showConfirmDialog(this, "Chưa nhập tên nguyên liệu");
        }
    }//GEN-LAST:event_btnTimKiemActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        try {
            int row = tblDanhSachNguyenLieu.getSelectedRow();
            if(row < 0 || row >= tblDanhSachNguyenLieu.getRowCount())
                throw new exception.ChuaChon();
            
            int soluong = Integer.parseInt(txtSoLuong.getText());
            if(soluong <= 0) throw new exception.SaiSo();
            int khuyenmai = Integer.parseInt(txtKhuyenMai.getText())  ;
            if(khuyenmai < 0 || khuyenmai > 100) throw new exception.SaiPhanTram();
            NguyenLieu nlchon = dsnl.get(row);
            NguyenLieuDung nld = new NguyenLieuDung();
            nld.setSoluong(soluong);
            nld.setGia(nlchon.getGiaBan());
            nld.setNl(nlchon);
            nld.setKhuyenmai(khuyenmai);
            NguyenLieuDungDAO nlDAO = new NguyenLieuDungDAO();
            nlDAO.themNguyenLieuDung(gdchitiet.getSlot().getMa(), nld);
            gdchitiet.capNhatNguyenLieuDung(nld);
        } catch (ChuaChon ex) {
            JOptionPane.showMessageDialog(this, "Chưa chọn nguyên liệu");
        }catch(NumberFormatException ex){
            JOptionPane.showMessageDialog(this, "Sai định dạng số");
        } catch (SaiSo ex) {
            JOptionPane.showMessageDialog(this, "Số lượng > 0");
        } catch (SaiPhanTram ex) {
            JOptionPane.showMessageDialog(this, "0 <= Khuyến mại <= 100");
        }

    }//GEN-LAST:event_btnThemActionPerformed

    private void btnXongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXongActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnXongActionPerformed

    private void backGroundMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backGroundMouseDragged
        this.setLocation((evt.getX()+this.getX())-X,( evt.getY()+this.getY())-Y);
    }//GEN-LAST:event_backGroundMouseDragged

    private void backGroundMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backGroundMousePressed
        X = evt.getX();
        Y = evt.getY();
    }//GEN-LAST:event_backGroundMousePressed

  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backGround;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnTimKiem;
    private javax.swing.JButton btnXong;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblDanhSachNguyenLieu;
    private javax.swing.JTextField txtKhuyenMai;
    private javax.swing.JTextField txtSoLuong;
    private javax.swing.JTextField txtTenNguyenLieu;
    // End of variables declaration//GEN-END:variables
}
