/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.nguyenlieu;

import dao.NguyenLieuDAO;
import exception.ChuaChon;
import exception.DeTrong;
import exception.SaiPhanTram;
import exception.SaiSo;
import java.awt.Color;
import java.awt.Font;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.NguyenLieu;
import model.NguyenLieuDung;
import view.slot.NhapThongTinSlotDatFrm;

/**
 *
 * @author My PC
 */
public class TimNguyenLieuFrm extends javax.swing.JFrame {

    /**
     * Creates new form TimNguyenLieuFrm
     */
    private ArrayList <NguyenLieu> dsnl;
    private DefaultTableModel bang;
    private NhapThongTinSlotDatFrm formnhap;
    private int X,Y;
    
    public TimNguyenLieuFrm(NhapThongTinSlotDatFrm formnhap) {
        this.setUndecorated(true);
        initComponents();
        setBackground(new Color(0, 0, 0, 0));
        setLocationRelativeTo(null);
        
        tblNguyenLieu.getTableHeader().setBackground(new Color(0, 0, 0));
        tblNguyenLieu.getTableHeader().setFont(new Font("Arial", 1 , 18));
        
        btnTimKiem.setBackground(new Color(0, 0, 0, 0));
        btnThem.setBackground(new Color(0, 0, 0, 0));
        btnXacNhan.setBackground(new Color(0, 0, 0, 0));
        
        this.formnhap = formnhap;
        bang = (DefaultTableModel) tblNguyenLieu.getModel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtTimNguyenLieu = new javax.swing.JTextField();
        btnTimKiem = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblNguyenLieu = new javax.swing.JTable();
        txtSoLuong = new javax.swing.JTextField();
        btnThem = new javax.swing.JButton();
        btnXacNhan = new javax.swing.JButton();
        txtKhuyenMai = new javax.swing.JTextField();
        backGround = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(723, 663));
        getContentPane().setLayout(null);

        txtTimNguyenLieu.setBackground(new java.awt.Color(224, 224, 254));
        txtTimNguyenLieu.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        txtTimNguyenLieu.setBorder(null);
        getContentPane().add(txtTimNguyenLieu);
        txtTimNguyenLieu.setBounds(240, 110, 230, 30);

        btnTimKiem.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnTimKiem.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnTimKiem.setPreferredSize(new java.awt.Dimension(48, 24));
        btnTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiemActionPerformed(evt);
            }
        });
        getContentPane().add(btnTimKiem);
        btnTimKiem.setBounds(476, 108, 123, 35);

        jScrollPane1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        tblNguyenLieu.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        tblNguyenLieu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã", "Tên nguyên liệu", "Đơn vị", "Dung tích", "Giá bán"
            }
        ));
        tblNguyenLieu.setRowHeight(30);
        jScrollPane1.setViewportView(tblNguyenLieu);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(50, 164, 630, 330);

        txtSoLuong.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        txtSoLuong.setBorder(null);
        getContentPane().add(txtSoLuong);
        txtSoLuong.setBounds(240, 509, 210, 30);

        btnThem.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnThem.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });
        getContentPane().add(btnThem);
        btnThem.setBounds(504, 508, 100, 35);

        btnXacNhan.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnXacNhan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnXacNhan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXacNhanActionPerformed(evt);
            }
        });
        getContentPane().add(btnXacNhan);
        btnXacNhan.setBounds(504, 552, 100, 35);

        txtKhuyenMai.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        txtKhuyenMai.setBorder(null);
        getContentPane().add(txtKhuyenMai);
        txtKhuyenMai.setBounds(240, 557, 210, 30);

        backGround.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Group 67.png"))); // NOI18N
        backGround.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                backGroundMouseDragged(evt);
            }
        });
        backGround.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                backGroundMousePressed(evt);
            }
        });
        getContentPane().add(backGround);
        backGround.setBounds(0, 0, 890, 650);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiemActionPerformed
        try {
            NguyenLieuDAO nlDAO = new NguyenLieuDAO();
            String ten = txtTimNguyenLieu.getText();
            ten = ten.trim();
            if(ten.length() == 0) throw new exception.DeTrong();
            dsnl = nlDAO.timNguyenLieu(ten);
            
            while(bang.getRowCount() > 0)
                bang.removeRow(0);
            for(NguyenLieu nl: dsnl)
                bang.addRow(nl.toObject());
        } catch (DeTrong ex) {
            JOptionPane.showConfirmDialog(this, "chưa nhập tên nguyên liệu");
        }
    }//GEN-LAST:event_btnTimKiemActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        try {
            int row = tblNguyenLieu.getSelectedRow();
            if(row < 0 || row >= tblNguyenLieu.getRowCount()) throw new exception.ChuaChon();
            int soluong = Integer.parseInt(txtSoLuong.getText())       ;
            if(soluong <= 0) throw new exception.SaiSo();
            int khuyenmai = Integer.parseInt(txtKhuyenMai.getText())  ;
            if(khuyenmai < 0 || khuyenmai > 100) throw new exception.SaiPhanTram();
            NguyenLieu nlchon = dsnl.get(row);
            NguyenLieuDung nld = new NguyenLieuDung();
            nld.setSoluong(soluong);
            nld.setGia(nlchon.getGiaBan());
            nld.setNl(nlchon);
            nld.setKhuyenmai(khuyenmai);
            formnhap.capNhatNguyenLieuDung(nld);
        } catch (ChuaChon ex) {
            JOptionPane.showMessageDialog(this, "chưa chọn nguyên liệu");
        }catch(NumberFormatException ex){
            JOptionPane.showMessageDialog(this, "sai định dạng số");
        } catch (SaiSo ex) {
            JOptionPane.showMessageDialog(this, "số lượng > 0");
        } catch (SaiPhanTram ex) {
            JOptionPane.showMessageDialog(this, "0 <= khuyenmai <= 100");
        }
                
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnXacNhanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXacNhanActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnXacNhanActionPerformed

    private void backGroundMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backGroundMouseDragged
        this.setLocation((evt.getX()+this.getX())-X,( evt.getY()+this.getY())-Y);
    }//GEN-LAST:event_backGroundMouseDragged

    private void backGroundMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backGroundMousePressed
        X = evt.getX();
        Y = evt.getY();
    }//GEN-LAST:event_backGroundMousePressed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backGround;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnTimKiem;
    private javax.swing.JButton btnXacNhan;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblNguyenLieu;
    private javax.swing.JTextField txtKhuyenMai;
    private javax.swing.JTextField txtSoLuong;
    private javax.swing.JTextField txtTimNguyenLieu;
    // End of variables declaration//GEN-END:variables
}
